name: Build image

on:
  workflow_call:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker build
      run: |
        docker build -t ghcr.io/dthenewbie/${{ github.event.repository.name }}:latest .
        docker push ghcr.io/dthenewbie/${{ github.event.repository.name }}:latest
